server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/enroll?allowPublicKeyRetrieval=TRUE&createDatabaseIfNotExist=TRUE&useSSL=FALSE&serverTimezone=America/Lima
        username: 'root'
        password: '1525'
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: 'create-drop'
