spring:
    datasource:
        url: jdbc:mysql://localhost:3306/student?allowPublicKeyRetrieval=TRUE&createDatabaseIfNotExist=TRUE&useSSL=FALSE&serverTimezone=America/Lima
        username: 'root'
        password: '1525'
    jpa:
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL5Dialect
        open-in-view: false
        hibernate:
            ddl-auto: 'create-drop'
